### ISSUE TITLE
Allow using remote file?

### ISSUE THREAD

**Issue by cmdcolin** [robertaboukhalil/bam.bio#1]
I was wondering if you think it could be possible to load remote files with your tool? I had looked at the htslib-js for this previously and did a bit of digging myself but never managed to do it

https://github.com/eilslabs/htslib-js/issues/2

There are multiple approaches I thought...samtools has "pluggable" retrieving mechanisms so they have their libcurl plugin...there is also just some approach which could make their raw socket code turn into xhr/fetch type things? Just wondering if you had any insight! great work :)

**Comment by robertaboukhalil** [comment]
Hey Colin,

Yes! When you run the "Sample queries" on bam.bio, it actually fetches an example .bam file from a URL. I initially tried getting that working using samtools' URL support directly, but that didn't really work.

Instead, I'm "lazy loading" a URL so that samtools thinks it's a regular file, but every time it asks for a certain byte range from that file, I can do a Range request query on the URL and give it the bytes it's expecting. Luckily, this is already implemented in [Emscripten's FS.createLazyFile() function](https://emscripten.org/docs/api_reference/Filesystem-API.html#FS.createLazyFile), so that's what I use [in the Aioli code](https://github.com/robertaboukhalil/aioli/blob/master/aioli.worker.js#L203).

(Aioli is a small tool I made to manage running WebAssembly code in a WebWorker, and managing files/Wasm calls)

The limitation though is that this only works on URLs that are CORS-enabled, unless you create e.g. a serverless function that proxies .bam URLs to add the right headers so it can be loaded in the browser.

Hope this helps!

**Comment by cmdcolin** [comment]
Very interesting. I see that, for example, specifying a full URL in the samtools view command gives an error though e.g. enter "samtools view http://jbrowse.org/code/JBrowse-1.16.6/docs/tutorial/data_files/volvox-sorted.bam ctgA"


```
setsockopt: Protocol not available
--
[E::hts_open_format] Failed to open file http://jbrowse.org/code/JBrowse-1.16.6/docs/tutorial/data_files/volvox-sorted.bam
samtools view: failed to open "http://jbrowse.org/code/JBrowse-1.16.6/docs/tutorial/data_files/volvox-sorted.bam" for reading: Bad file descriptor

```

**Comment by robertaboukhalil** [comment]
Yes, bam.bio is mostly intended for local files so I didn't expose the support for URLs directly. The hack around it would be to open the dev console and type:

```javascript
app.mount([
  "http://jbrowse.org/code/JBrowse-1.16.6/docs/tutorial/data_files/volvox-sorted.bam",
  "http://jbrowse.org/code/JBrowse-1.16.6/docs/tutorial/data_files/volvox-sorted.bam.bai"
])
```

That will do the lazy loading I described above.

Then, running `samtools view /urls/volvox-sorted.bam ctgA` should work but it seems that jbrowse URL is not CORS-enabled, so I get this error:

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://jbrowse.org/code/JBrowse-1.16.6/docs/tutorial/data_files/volvox-sorted.bam.
(Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
```

But if you add the expect CORS headers, it should work.

**Comment by cmdcolin** [comment]
Thanks a ton. If you have any ability to add actual remote URLs just similar to how you can do samtools view http://... that would be sweet but that is a good workaround
